name: dino_run
description: A 2D infinite side scroller.

publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flame: ^1.18.0
  flame_audio: ^2.10.2
  hive: 2.2.3
  path_provider: ^2.1.3
  provider: ^6.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  confetti: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_donation_buttons: ^0.4.10


flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true



dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0




flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/parallax/
    - assets/images/parallaxl/
    - assets/images/AngryPig/
    - assets/images/Bat/
    - assets/images/Rino/
    - assets/images/Bee/
    - assets/images/BlueBird/
    - assets/images/Chameleon/
    - assets/images/Rocks/
    - assets/audio/

  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide/Audiowide-Regular.ttf


